### PR TITLE
Fix lai code

### PR DESCRIPTION
**Pull request by nguyenquanglinh2898**
## Related Tickets:
- [#31371](https://edu-redmine.sun-asterisk.vn/issues/31371)

## WHAT this PR does?
- sửa lại code lần 1
## Notes Impacted Areas:
- N/A.

## Attachments:
- N/A.

### CODE REVIEW

**Comment by nguyenquanglinh2898** [comment]
ready

**Review by huyenttm-0901 — COMMENTED** [review]
suwar nhes

**Comment by nguyenquanglinh2898** [comment]
ready

**Comment by nguyenquanglinh2898** [comment]
ready

**Pull request merged**
